spring.application.name=novo_siga
spring.main.banner-mode=off

# Configurações do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/db_novosiga
spring.datasource.username=postgres
spring.datasource.password=123456

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Configurações do Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=false

# Silencia logs gerais do Spring e Tomcat
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.apache.catalina=WARN
logging.level.org.apache.tomcat=WARN

# Mantém visíveis os logs do Banco de Dados, SQL e do seu projeto
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.com.zaxxer.hikari=INFO
logging.level.com.novosiga=INFO

# Limitar o tamanho máximo do arquivo de upload para 2MB
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB